on:
  push:
    branches:
  pull_request:
    branches:

name: main
jobs:
  linux:
    name: 'Linux'
    container:
      image: ubuntu:16.04
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: ./install.dependencies.sh
      working-directory: build/linux

    - name: Clone ImageMagick libraries
      run: ./checkout.sh linux
      working-directory: src/ImageMagick

    - name: Build libraries
      run: ../../../build/linux/build.libraries.sh ../../../build/libraries
      working-directory: src/ImageMagick/libraries

    - name: Build ImageMagick
      run: ../../../build/linux/build.ImageMagick.sh
      working-directory: src/ImageMagick/libraries

    - name: Build Native
      run: ../../build/linux/build.Native.sh
      working-directory: src/Magick.Native

    - name: Copy Native
      run: ../../build/linux/copy.Native.sh ../../artifacts
      working-directory: src/Magick.Native

    - name: Upload library
      uses: actions/upload-artifact@v1
      with:
        name: linux
        path: artifacts

  linux_openmp:
    name: 'Linux OpenMP'
    container:
      image: ubuntu:16.04
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: ./install.dependencies.sh
      working-directory: build/linux-openmp

    - name: Clone ImageMagick libraries
      run: ./checkout.sh linux
      working-directory: src/ImageMagick

    - name: Build libraries
      run: ../../../build/linux-openmp/build.libraries.sh ../../../build/libraries
      working-directory: src/ImageMagick/libraries

    - name: Build ImageMagick
      run: ../../../build/linux-openmp/build.ImageMagick.sh
      working-directory: src/ImageMagick/libraries

    - name: Build Native
      run: ../../build/linux-openmp/build.Native.sh
      working-directory: src/Magick.Native

    - name: Copy Native
      run: ../../build/linux-openmp/copy.Native.sh ../../artifacts
      working-directory: src/Magick.Native

    - name: Upload library
      uses: actions/upload-artifact@v1
      with:
        name: linux-openmp
        path: artifacts

  linux_musl:
    name: 'Linux musl'
    container:
      image: alpine:3.12
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: ./install.dependencies.sh
      working-directory: build/linux-musl

    - name: Clone ImageMagick libraries
      run: ./checkout.sh linux
      working-directory: src/ImageMagick

    - name: Build libraries
      run: ../../../build/linux-musl/build.libraries.sh ../../../build/libraries
      working-directory: src/ImageMagick/libraries

    - name: Build ImageMagick
      run: ../../../build/linux-musl/build.ImageMagick.sh
      working-directory: src/ImageMagick/libraries

    - name: Build Native
      run: ../../build/linux-musl/build.Native.sh
      working-directory: src/Magick.Native

    - name: Copy Native
      run: ../../build/linux-musl/copy.Native.sh ../../artifacts
      working-directory: src/Magick.Native

    - name: Upload library
      uses: actions/upload-artifact@v1
      with:
        name: linux-musl
        path: artifacts
